### ISSUE TITLE
14페이지 비행페이지

### ISSUE THREAD

**Issue by rnjswngus275** [CBNU-DoReMiFa/stop_and_flight#27]
주현+규원

- [x] viewpager생성
- [x] 허용앱 팝업
- [x] 비상탈출 -> 실패페이지
- [x] 성공페이지 => #43

**Comment by kyoowon** [comment]
허용된 앱 사용하기 기능 
-  현재 다른 앱을 실행할 수 있음.
+ 앞으로 작성에서 사용자가 설정된 앱만이 보여줄 수 있도록 추가 예정.
비상탈출 기능
 - 현재 버튼에 클릭시 팝업이 뜨면서 정말로 비행 취소를 할 것이지 확인.
 + 여기서 탈출권이 추가된다면 제한된 값안으로 버튼 활성화 예정.
 + 실패하기 페이지 생성시 연결.
