### ISSUE TITLE
디자인 

### ISSUE THREAD

**Issue by rnjswngus275** [CBNU-DoReMiFa/stop_and_flight#87]
[https://kmong.com/gig/286873](https://kmong.com/gig/286873) : 로고 + 상세페이지
[https://kmong.com/gig/286873](https://kmong.com/gig/286873) : 로고만
[https://kmong.com/gig/286078](https://kmong.com/gig/286078) : 로고만

**Comment by kimaram** [comment]
https://kmong.com/gig/19912

**Comment by kyoowon** [comment]
https://kmong.com/gig/270685
https://kmong.com/gig/85293

**Comment by rnjswngus275** [comment]
앱 아이콘
스플래시 이미지
상세 페이지
도장 일러스트

**Comment by rnjswngus275** [comment]
https://kmong.com/gig/300658
